{
 "title": "High Level Application metrics",
 "description": "Application metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"^5..$\"}[1m]))/sum(increase(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "TPM",
   "type": "graph",
   "description": "Transactions per minutes",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (path, method, code)  * 60",
     "legendFormat": "{{method}} {{path}} {{code}}"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, route, method))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, route, method))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_nodejs_external_memory_bytes / 1024) by (route)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_process_cpu_seconds_total[5m])) * 100)"
    }
   ]
  }
 ]
}